# Generated by Django 4.2 on 2024-02-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membership_delete_datenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='year',
            field=models.IntegerField(),
        ),
    ]
