# Generated by Django 4.2 on 2024-02-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_membership_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Family', models.CharField(max_length=255)),
                ('codemeli', models.CharField(max_length=255)),
            ],
        ),
    ]
