# Generated by Django 4.2.9 on 2024-02-13 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_membership_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kardan',
        ),
        migrations.AddField(
            model_name='membership',
            name='Family',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='codemeli',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
