# Generated by Django 4.2.9 on 2024-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_delete_kardan_membership_family_membership_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Family',
            field=models.CharField(max_length=255, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='codemeli',
            field=models.CharField(max_length=255, unique=True, verbose_name='کد ملی'),
        ),
    ]
